### ISSUE TITLE
Deal with stores

### ISSUE THREAD

**Issue by maxguzenski** [gaearon/flux-react-router-example#19]
Hi @gaearon 

I take a close look on your example and some post from you on [google groups](https://groups.google.com/forum/#!searchin/reactjs/flux$20paginating/reactjs/jbh50-GJxpg/Aln9a_Icy3IJ) but I have some question that maybe you can help me.

I have a social network, pretty like facebook, and my first approach was to have a store to each page, so I end up with SearchStore, FeedStore, FriendStore, etc... that keep duplicated data (like user{name, avatar, etc}) into each one.

Good side is that when I make a fresh search, I replace old data with new one that will remove users data that is not used anymore (server always will return necessary users). 

But with your approach (Content Store) I will end up with 5k, 10k, 300k users data that is not used anymore, even if it is used, server will return fresh users data. Is this not a issue? How di you deal with this?

**Comment by gaearon** [comment]
Depends heavily on your app. Even in a social network, I highly doubt a user encounters 300k users while just browsing their feed, replying to messages, etc, during one session. Do your users keep the tab open for weeks?

>Good side is that when I make a fresh search, I replace old data with new one that will remove users data that is not used anymore (server always will return necessary users).

It's the same with content stores. Whenever new data comes in, they'll merge it in. There is no stale data problem in my example if that's what you mean.

If keeping currently unused data really proves to be an issue (profile it! it may not), you can add some manual garbage collection. For example, when user enters a page (such as FeedPage), mark it as visible, when user leaves it, mark it as not visible. Clean up all entities that are not used by any visible page. It's more work, and more potential room for mistakes, so I didn't implement this. Honestly I don't see the point because in a social network it's unlikely you'll browse 300k items in one session. And even if you do, it won't necessarily cause perf problems.
