### ISSUE TITLE
Delete a content store?

### ISSUE THREAD

**Issue by cuongcua90** [gaearon/flux-react-router-example#30]
Hi, I have a question.

When content store belongs to a list store or indexed list store. How should I implements when delete that store?

Thank you

**Comment by gaearon** [comment]
Two options I found practical:

* Just reload the app if deleting is a rare operation.
* If it's common, you can make “deletion” a status rather than real deletion. E.g. you may have `status` field in the model, set it to `DELETED` when an item is deleted, have UI always show `DELETED` items as non existant.
